import{a as q,S as E,i as a}from"./assets/vendor-BNibzuFn.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const B="https://pixabay.com/api/",R="52538556-e7ad6b62877d90490937495df";async function f(r,t=1,n=15){const i={key:R,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:n};return(await q.get(B,{params:i})).data}const g=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more");let $=new E(".gallery a",{captionsData:"alt",captionDelay:250});function y(r){const t=r.map(({webformatURL:n,largeImageURL:i,tags:e,likes:o,views:s,comments:b,downloads:S})=>`
      <li class="gallery-item">
        <a href="${i}">
          <img src="${n}" alt="${e}" loading="lazy" />
        </a>
        <div class="image-info">
          <p>👍 ${o}</p>
          <p>👁️ ${s}</p>
          <p>💬 ${b}</p>
          <p>⬇️ ${S}</p>
        </div>
      </li>`).join("");g.insertAdjacentHTML("beforeend",t),$.refresh()}function M(){g.innerHTML=""}function L(){m.classList.add("is-loading")}function v(){m.classList.remove("is-loading")}function w(){h.classList.add("visible")}function u(){h.classList.remove("visible")}const O=document.querySelector("#search-form"),P=document.querySelector(".load-more");let c="",l=1;const d=15;let p=0;O.addEventListener("submit",async r=>{if(r.preventDefault(),c=r.currentTarget.elements.searchQuery.value.trim(),!c){a.warning({title:"Warning",message:"Enter a search query",position:"topRight"});return}l=1,M(),u(),L();try{const t=await f(c,l,d);if(p=t.totalHits,t.hits.length===0){a.error({title:"No Results",message:"No images found. Try another query!",position:"topRight"});return}y(t.hits),p>d&&w()}catch{a.error({title:"Error",message:"Something went wrong.",position:"topRight"})}finally{v()}});P.addEventListener("click",async()=>{l+=1,L(),u();try{const r=await f(c,l,d);y(r.hits),l*d>=p?(u(),a.info({title:"End of results",message:"You've reached the end.",position:"topRight"})):w();const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}catch{a.error({title:"Error",message:"Something went wrong.",position:"topRight"})}finally{v()}});
//# sourceMappingURL=index.js.map
